server:
  port: 8080
  servlet:
    context-path: '/api/'

database:
  url: jdbc:h2:mem:ms-spring?useSSL=false&serverTimezone=UTC
  username: sa
  password:

spring:
  profiles:
    active: test

  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: true
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: '/h2'

  jackson:
    deserialization:
      fail-on-unknown-properties: true
    time-zone: 'America/Sao_Paulo'

logging:
  level:
    root: INFO
    org.springframework.web.client: INFO